### ISSUE TITLE
traverson-hal support?

### ISSUE THREAD

**Issue by jtatum** [basti1302/traverson-angular#10]
Is there an easy way to pull traverson-hal into traverson-angular?

**Comment by jtatum** [comment]
Never mind. Turns out there's a lovely example in https://github.com/basti1302/traverson-angular/blob/master/browser/example/hal.js

**Comment by basti1302** [comment]
Since you are the second person asking this question, I added docs for this and a link to the example. 

https://github.com/basti1302/traverson-angular/#traverson-angular-with-media-type-plug-ins

Had planned to do this already, thanks for the ping.
