### ISSUE TITLE
Tests do not cover other functions, they test only get()

### ISSUE THREAD

**Issue by binarykitchen** [basti1302/traverson-angular#2]
For example the `post()` is missing ... no idea here how to call the promisified post()?

**Comment by binarykitchen** [comment]
I guess something like this would solve it:

```js
  function promisify(that, originalMethod, argsArray) {
    var deferred = $q.defer();
    var argsArray = argsArray || [];

    var callback = function(err, result, uri) {
      if (err) {
        err.result = result;
        err.uri = uri;
        deferred.reject(err);
      } else {
        deferred.resolve(result);
      }
    };

    argsArray.push(callback);

    originalMethod.apply(that, argsArray);
    return deferred.promise;
  }

...

  Builder.prototype.post = function(body) {
    return promisify(this, originalMethods.post, [body]);
  };
```

**Comment by basti1302** [comment]
Yep, there's definitely a problem with the args to put/post/patch. Thanks for the report and the proposed fix. I'll take a look.

However, if you need this fix to be merged and published in the next 24 hours (as you said on Twitter), I doubt I can make that happen. Remember that I do this in my free time and have other responsibilities besides maintaining this package.

**Comment by binarykitchen** [comment]
Totally understand and respect that. But there are quite a lot of bugs ... found a couple of more, so make sure you really cover lots of different scenarios.

**Comment by basti1302** [comment]
I'm currently knee deep in some other projects. This is why work on Traverson has come to a halt for the last 2-3 months. I'll start working on Traverson again soon (~2 weeks) and will have a look at it then. Sorry for the delay.

**Comment by basti1302** [comment]
post/put/patch/delete works now, thanks to contributions from @binarykitchen.

Also, the latest commit adds extensive test coverage for post/put/patch/delete.
