### ISSUE TITLE
Passing custom options to angular $http

### ISSUE THREAD

**Issue by jinder** [basti1302/traverson-angular#21]
I've looked through the code and noticed that mapOptions only permits certain options to be sent to $http.  I'd like to send an additional option through, but can't see a way of doing this without changing the function.  Is there a reason why it's restrictive?  Would it be possible to change this behaviour?

Thanks

**Comment by basti1302** [comment]
The reason might be that Traverson exposes uses the request/request API as its interface for HTTP options. traverson-angular maps this to the $http interface. To do this, you probably need to do the mapping manual for everything you want to map.

I agree that this is less than ideal. I'm totally open for suggestions on how to improve this. Do you have a good idea how to do this?

**Comment by jinder** [comment]
I guess one solution could be to have a 'angularHttpOptions' object attached to the options object.  Then add a mapAngularHttpOptions function that works like the others, except it adds all the keys directly to the options object.

It's a little bit ugly, but not too ugly :)
