### ISSUE TITLE
Add example of including Media Type Plug-ins?

### ISSUE THREAD

**Issue by nilsnh** [basti1302/traverson-angular#7]
Hi there,

I'm quite interested in moving to 1.0.0+ but I was not able to find a good example of how to include for instance the json-hal plugin in traverson-angular. Could an Angularjs example be added to the docs?

Thanks for the good work.

Best regards,
Nils

**Comment by basti1302** [comment]
I added an example:

* https://github.com/basti1302/traverson-angular/blob/master/browser/example/hal.html
* https://github.com/basti1302/traverson-angular/blob/master/browser/example/hal.js

But it really works the same as for traverson core, there is no difference to integrate media type plug-ins when using traverson-angular.

TL;DR: 
* Add traverson-hal.min.js (script tag or whatever)
* Register the media type: `traverson.registerMediaType(TraversonJsonHalAdapter.mediaType, TraversonJsonHalAdapter);`
* If necessary force Traverson to use HAL with `.jsonHal()`
* If necessary, add Accept headers so your server knows you want to talk HAL: `.withRequestOptions({ headers: { 'accept': 'application/hal+json' } })`
