### ISSUE TITLE
Possible to use $http as http provider for Traverson

### ISSUE THREAD

**Issue by sdbondi** [basti1302/traverson-angular#8]
I have defined interceptors and configured $http. 
Would it be possible for Traverson to use $http as it's provider?
If so, could we include an adapter in this library?

Thanks :smile:

**Comment by basti1302** [comment]
You might be able to do that using the `.withRequestLibrary(request)` configuration method on Traverson's request builder. Basically you would need to write an adapter that uses $http internally but offers an API that is a small subset of https://github.com/request/request.

Take a look at https://github.com/basti1302/traverson/blob/master/browser/lib/shim/request.js which retrofits the superagent library to emulate this required API, this should give you an idea.

If you succeed, I would be happy to integrate this adapter into traverson-angular.

**Comment by sdbondi** [comment]
After taking a look at the docs I did find `.withRequestLibrary`, but was busy looking through the code to figure out how to use it. Sure there is much more documentation that could be contributed there. 

Thanks - that gives me a good idea of the API that needs to be exposed.

**Comment by basti1302** [comment]
> Sure there is much more documentation that could be contributed there. 

Sure, go ahead :-)

**Comment by basti1302** [comment]
@sdbondi Did anything ever come out of this? Did you actually implement this wrapper for `$http`? I would *love* to see the results, even if incomplete or specific to your use case.

**Comment by sdbondi** [comment]
@basti1302 I did! It's not complete and as you say $http only has a subset of the of request. Here is my work https://github.com/fixate/traverson-angular/blob/feature/ngHttpAdapter/traverson-angular.js

Hope something can come from it as I'm not using it. I decided not to use traverson in the end for a smaller library which I had to modify to include http write verbs.

**Comment by basti1302** [comment]
Cool! Will have a look at it and thanks for the udpate. Out of curiosity, which library did you go with?

**Comment by sdbondi** [comment]
Hyperagent. I'm eager to use traverson in the future, it's a great library! For now I'm still feeling my way around hypermedia apis (aren't we all :smile:) so smaller is better. 

Thanks for the great work @basti1302

**Comment by sdbondi** [comment]
Oh ye, in the adapter, I wasn't sure how to get $http to give me the XHR response which is required by traverson. That's pretty much where I stopped.

**Comment by basti1302** [comment]
On second thought, I'll leave this open.

Note to self: sbondi's branch has been transferred to https://github.com/basti1302/traverson-angular/tree/feature/ngHttpAdapter

**Comment by basti1302** [comment]
FWIW, I finished the work started by @sdbondi so this should work now. It has landed in release 2.1.0.

**Comment by sdbondi** [comment]
Awesome, thanks @basti1302!
